/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Environment {
  constructor()
  /** Renders with this environment. `Env` is required so custom filters can call back into JavaScript synchronously. */
  renderString(template: string, context: any): string
  /** Same as [`render_string`], but context is a JSON string (see [`render_string_from_json`]). */
  renderStringFromJson(template: string, contextJson: string): string
  setAutoescape(enabled: boolean): void
  setDev(enabled: boolean): void
  /** Fixes the PRNG used by `| random` for reproducible tests (omit / pass `undefined` to use a fresh non-deterministic seed per render). */
  setRandomSeed(seed?: number | undefined | null): void
  /** Registers `(input, ...args) => any`. Overrides a built-in filter with the same name. */
  addFilter(name: string, func: unknown): void
  /** Registers `(value, ...args) => boolean` (truthy return) for `is` tests and for `select` / `reject`. Built-in tests (`odd`, `even`, …) take precedence over the same name. */
  addTest(name: string, func: unknown): void
  /** Custom tag extension (Nunjucks `addExtension`): `tags`, optional `blocks` map (opening tag → end tag name), and `process(context, args, body)` — `body` is `null` for simple tags. */
  addExtension(extensionName: string, tags: Array<string>, blocks: Record<string, string> | undefined | null, process: unknown): void
  /** Returns whether a custom extension with this name is registered (Nunjucks `hasExtension`). */
  hasExtension(name: string): boolean
  /** Returns an introspection-only descriptor for a registered extension (tags + block end tags). */
  getExtension(name: string): ExtensionDescriptor | null
  /** Unregisters a custom extension by name (Nunjucks `removeExtension`). Returns `true` if it existed. */
  removeExtension(name: string): boolean
  /** Registers a global: JSON-serializable value, or a **JavaScript function** invoked for `{{ name(...) }}` (Nunjucks-style keyword args as a trailing object). See `NUNJUCKS_PARITY.md` (P1). */
  addGlobal(name: string, value: unknown): void
  /** Subset of Nunjucks `configure`: `autoescape`, `dev`, `throwOnUndefined`, `trimBlocks`, `lstripBlocks`, and `tags` are applied. */
  configure(opts: ConfigureOptions): void
  /**
   * Sync callback `(name: string) => string | null | { src: string }`. `null` / `undefined` JSON as
   * `null` means template not found. Replaces any previous loader (same as `setTemplateMap` /
   * `setLoaderRoot`). Does not use the named parse cache per key (sources may change arbitrarily).
   */
  setLoaderCallback(callback: unknown): void
  /** Clears parse caches for named templates and inline `renderString` / `Template` sources (Nunjucks `invalidateCache`). */
  invalidateCache(): void
  /** Loads a named template from this environment’s loader (same idea as Nunjucks `getTemplate`). */
  getTemplate(name: string, eagerCompile?: boolean | undefined | null): Template
  /** Sets an in-memory template map (`name` → source). Enables `renderTemplate`, `{% include %}`, `{% extends %}`, etc. */
  setTemplateMap(map: Record<string, string>): void
  /**
   * Loads named templates from a directory on disk (relative paths under `root`). Replaces any
   * previous loader. See [`runjucks_core::FileSystemLoader`].
   */
  setLoaderRoot(path: string): void
  /** Renders a named template from the map set via [`set_template_map`]. */
  renderTemplate(name: string, context: any): string
}
export type JsEnvironment = Environment

/** Nunjucks-compatible compiled template: inline source or a named template from the environment loader. */
export declare class Template {
  /** `new Template(src, env?, path?, eagerCompile?)` — mirror [`compile`]. */
  constructor(src: string, env?: JsEnvironment | undefined | null, path?: string | undefined | null, eagerCompile?: boolean | undefined | null)
  render(context: any): string
  /** Optional path for this template (Nunjucks uses it for errors; inline [`compile`] / `new Template` only). */
  get path(): string | null
}
export type JsTemplate = Template

/** `compile(src, env?, path?, eagerCompile?)` — Nunjucks-compatible factory for [`Template`]. */
export declare function compile(src: string, env?: Environment | undefined | null, path?: string | undefined | null, eagerCompile?: boolean | undefined | null): Template

/** Nunjucks-style module `configure(opts?)` — sets the default environment used by [`render`]. */
export declare function configure(opts?: ConfigureOptions | undefined | null): Environment

export interface ConfigureOptions {
  autoescape?: boolean
  dev?: boolean
  throwOnUndefined?: boolean
  trimBlocks?: boolean
  lstripBlocks?: boolean
  tags?: TagsOptions
}

export interface ExtensionDescriptor {
  name: string
  tags: Array<string>
  blocks: Record<string, string>
}

/** Top-level `render(name, ctx)` using the environment from [`configure_default`]. */
export declare function render(name: string, context: any): string

export declare function renderString(template: string, context: any): string

/**
 * Like [`render_string`], but the context is **JSON text** (e.g. from `JSON.stringify(ctx)` in JS).
 * Skips N-API object→JSON conversion on the JS side when you already have a string; Rust still
 * parses to `serde_json::Value` before render. Build with `--features fast-json` on `runjucks-napi`
 * for a faster JSON parse when profiling shows ingress dominates.
 */
export declare function renderStringFromJson(template: string, contextJson: string): string

/** Clears the module-level default environment (for tests; matches Nunjucks `reset`). */
export declare function reset(): void

export interface TagsOptions {
  blockStart?: string
  blockEnd?: string
  variableStart?: string
  variableEnd?: string
  commentStart?: string
  commentEnd?: string
}
